# Generated by Django 5.0.3 on 2024-04-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pages', '0002_alter_comment_user_alter_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
